export const EVENT_EVENTS = {
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_UNPUBLISHED: 'EVENT_UNPUBLISHED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_DELETED: 'EVENT_DELETED',

  ORGANIZER_ASSIGNED: 'ORGANIZER_ASSIGNED',
  ORGANIZER_REMOVED: 'ORGANIZER_REMOVED',

  REGISTRATION_CREATED: 'EVENT_REGISTRATION_CREATED',
  REGISTRATION_CANCELLED: 'EVENT_REGISTRATION_CANCELLED',

  VENUE_CREATED: 'VENUE_CREATED',
  VENUE_UPDATED: 'VENUE_UPDATED',
  VENUE_DELETED: 'VENUE_DELETED',

  SPEAKER_CREATED: 'SPEAKER_CREATED',
  SPEAKER_UPDATED: 'SPEAKER_UPDATED',
  SPEAKER_DELETED: 'SPEAKER_DELETED',

  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_UPDATED: 'SESSION_UPDATED',
  SESSION_DELETED: 'SESSION_DELETED',
  SESSION_ORDER_UPDATED: 'SESSION_ORDER_UPDATED',

  SESSION_REMINDER_SCHEDULED: 'SESSION_REMINDER_SCHEDULED',
} as const;

export const EVENT_RESOURCE_TYPE = {
  EVENT: 'event',
  ORGANIZER: 'event:organizer',
  REGISTRATION: 'event:registration',
  VENUE: 'event:venue',
  SPEAKER: 'event:speaker',
  SESSION: 'event:session',
  SCHEDULE: 'event:schedule',
  NOTE: 'event:session_note',
} as const;
