export enum Role {
  ADMIN = 'ADMIN',
  ATTENDEE = 'ATTENDEE',
  SPONSOR = 'SPONSOR',
  VENDOR = 'VENDOR',
  PROVIDER = 'PROVIDER',
  EVENT_OWNER = 'EVENT_OWNER',
  ORGANIZER = 'ORGANIZER',
  MEDIA = 'MEDIA',
}
